// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ks2itoY8vQqyiFe2t8uOFabFihnu6vQ',
    appId: '1:798139723674:android:b08e9b39ba04a186925423',
    messagingSenderId: '798139723674',
    projectId: 'buku-kontak-b8de1',
    storageBucket: 'buku-kontak-b8de1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsrfmZFostEeXLdfOknqijkXE6dAzbt5Y',
    appId: '1:798139723674:ios:5cca0f2569b0533d925423',
    messagingSenderId: '798139723674',
    projectId: 'buku-kontak-b8de1',
    storageBucket: 'buku-kontak-b8de1.firebasestorage.app',
    iosBundleId: 'com.example.kontakForm',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_kHoS4813d0D2eA5Xt1lInWxctRp9TiA',
    appId: '1:798139723674:web:bcb4bfb2d821c142925423',
    messagingSenderId: '798139723674',
    projectId: 'buku-kontak-b8de1',
    authDomain: 'buku-kontak-b8de1.firebaseapp.com',
    storageBucket: 'buku-kontak-b8de1.firebasestorage.app',
    measurementId: 'G-VL1Q7QBW07',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsrfmZFostEeXLdfOknqijkXE6dAzbt5Y',
    appId: '1:798139723674:ios:5cca0f2569b0533d925423',
    messagingSenderId: '798139723674',
    projectId: 'buku-kontak-b8de1',
    storageBucket: 'buku-kontak-b8de1.firebasestorage.app',
    iosBundleId: 'com.example.kontakForm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_kHoS4813d0D2eA5Xt1lInWxctRp9TiA',
    appId: '1:798139723674:web:35ca1b71ca754bf5925423',
    messagingSenderId: '798139723674',
    projectId: 'buku-kontak-b8de1',
    authDomain: 'buku-kontak-b8de1.firebaseapp.com',
    storageBucket: 'buku-kontak-b8de1.firebasestorage.app',
    measurementId: 'G-WZEYQ7G94D',
  );
}
